import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { CameraView, useCameraPermissions, type BarcodeScanningResult } from "expo-camera";
import { useIsFocused } from "@react-navigation/native";
import { router, useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

export default function ScannerScreen() {
  const { mode = "sale", productId = "new" } = useLocalSearchParams<{ mode?: "sale" | "product"; productId?: string }>(); const [permission, requestPermission] = useCameraPermissions(); const isFocused = useIsFocused(); const [scanned, setScanned] = useState(false); const [cameraKey, setCameraKey] = useState(0); const [cameraError, setCameraError] = useState<string | null>(null); const [isCameraReady, setIsCameraReady] = useState(false);
  useEffect(() => { if (isFocused) { setScanned(false); setCameraError(null); setIsCameraReady(false); setCameraKey((value) => value + 1); } }, [isFocused, permission?.granted]);
  const requestCamera = useCallback(async () => { const result = await requestPermission(); if (result.granted) { setCameraError(null); setScanned(false); setCameraKey((value) => value + 1); } }, [requestPermission]);
  const handleScan = ({ data }: BarcodeScanningResult) => { setScanned(true); if (mode === "product") router.replace({ pathname: "/product/[id]", params: { id: productId, barcode: data } } as never); else router.replace({ pathname: "/(tabs)/sale", params: { scannedBarcode: data } } as never); };
  if (!permission) return <View style={styles.fallback}><Text style={styles.fallbackText}>جارٍ تجهيز الكاميرا...</Text></View>;
  if (!permission.granted) return <View style={styles.fallback}><MaterialIcons name="photo-camera" size={45} color="#146C5A" /><Text style={styles.permissionTitle}>نحتاج إذن الكاميرا</Text><Text style={styles.permissionText}>يُستخدم الإذن لمسح الباركود بسرعة وإضافة صور المنتجات.</Text><Pressable onPress={() => { void requestCamera(); }} style={({ pressed }) => [styles.permissionButton, pressed && styles.pressed]}><Text style={styles.permissionButtonText}>السماح بالكاميرا</Text></Pressable><Pressable onPress={() => router.back()}><Text style={styles.cancelText}>رجوع</Text></Pressable></View>;
  if (cameraError) return <View style={styles.fallback}><MaterialIcons name="error-outline" size={45} color="#C43D4B" /><Text style={styles.permissionTitle}>تعذر تشغيل الكاميرا</Text><Text style={styles.permissionText}>{cameraError}</Text><Pressable onPress={() => { setCameraError(null); setCameraKey((value) => value + 1); }} style={({ pressed }) => [styles.permissionButton, pressed && styles.pressed]}><Text style={styles.permissionButtonText}>إعادة المحاولة</Text></Pressable><Pressable onPress={() => router.back()}><Text style={styles.cancelText}>رجوع</Text></Pressable></View>;
  return <View style={styles.container}>{isFocused ? <CameraView key={cameraKey} style={StyleSheet.absoluteFill} facing="back" onCameraReady={() => setIsCameraReady(true)} onMountError={(event) => setCameraError(event.message || "تعذر الوصول إلى كاميرا الجهاز.")} barcodeScannerSettings={{ barcodeTypes: ["ean13", "ean8", "upc_a", "upc_e", "code128", "code39", "qr"] }} onBarcodeScanned={scanned || !isCameraReady ? undefined : handleScan} /> : null}<View style={styles.overlay}><View style={styles.top}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.closeButton, pressed && styles.pressed]}><MaterialIcons name="close" size={26} color="#FFFFFF" /></Pressable><View><Text style={styles.title}>مسح باركود</Text><Text style={styles.subtitle}>{isCameraReady ? "وجّه الكاميرا نحو الباركود" : "جارٍ تشغيل الكاميرا..."}</Text></View></View><View style={styles.scanArea}><View style={styles.cornerTopRight} /><View style={styles.cornerTopLeft} /><View style={styles.cornerBottomRight} /><View style={styles.cornerBottomLeft} /><View style={styles.scanLine} /></View><Text style={styles.help}>سيتم التعرف على الرمز تلقائيًا دون التقاط صورة</Text></View></View>;
}
const corner = { position: "absolute" as const, width: 34, height: 34, borderColor: "#7CE2C2" };
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: "#0B1713" }, overlay: { flex: 1, paddingTop: 64, paddingHorizontal: 24, backgroundColor: "rgba(4, 18, 12, 0.22)" }, top: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "flex-start" }, closeButton: { width: 45, height: 45, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(0,0,0,0.38)" }, title: { color: "#FFFFFF", fontSize: 22, lineHeight: 29, fontWeight: "800", textAlign: "right" }, subtitle: { color: "#E0F1EA", fontSize: 13, lineHeight: 19, textAlign: "right" }, scanArea: { height: 220, marginTop: 115, marginHorizontal: 4, borderRadius: 24, backgroundColor: "rgba(0,0,0,0.15)" }, cornerTopRight: { ...corner, right: 0, top: 0, borderRightWidth: 4, borderTopWidth: 4, borderTopRightRadius: 22 }, cornerTopLeft: { ...corner, left: 0, top: 0, borderLeftWidth: 4, borderTopWidth: 4, borderTopLeftRadius: 22 }, cornerBottomRight: { ...corner, right: 0, bottom: 0, borderRightWidth: 4, borderBottomWidth: 4, borderBottomRightRadius: 22 }, cornerBottomLeft: { ...corner, left: 0, bottom: 0, borderLeftWidth: 4, borderBottomWidth: 4, borderBottomLeftRadius: 22 }, scanLine: { position: "absolute", left: 19, right: 19, top: "50%", height: 2, backgroundColor: "#7CE2C2", shadowColor: "#7CE2C2", shadowOpacity: 0.9, shadowRadius: 7 }, help: { color: "#FFFFFF", fontSize: 14, lineHeight: 21, textAlign: "center", marginTop: 26 }, fallback: { flex: 1, alignItems: "center", justifyContent: "center", gap: 13, paddingHorizontal: 35, backgroundColor: "#F7FAF8" }, fallbackText: { color: "#61726B", fontSize: 15 }, permissionTitle: { color: "#16201D", fontSize: 20, lineHeight: 28, fontWeight: "800" }, permissionText: { color: "#61726B", fontSize: 14, lineHeight: 21, textAlign: "center" }, permissionButton: { minHeight: 49, paddingHorizontal: 18, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: "#146C5A", marginTop: 6 }, permissionButtonText: { color: "#FFFFFF", fontSize: 15, lineHeight: 21, fontWeight: "800" }, cancelText: { color: "#146C5A", fontSize: 15, lineHeight: 21, fontWeight: "800", marginTop: 10 }, pressed: { opacity: 0.72 } });
