import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { EmptyState, PrimaryButton, ProductRow, StatCard } from "@/components/pos-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useInventory } from "@/lib/inventory/inventory-provider";

export default function HomeScreen() {
  const { isReady, products, sales, settings } = useInventory(); const todayKey = new Date().toISOString().slice(0, 10); const todaySales = sales.filter((sale) => sale.createdAt.slice(0, 10) === todayKey).reduce((total, sale) => total + sale.total, 0); const inventoryValue = products.reduce((total, product) => total + product.quantity * (product.purchasePrice ?? 0), 0); const lowProducts = products.filter((product) => product.quantity > 0 && product.quantity <= settings.lowStockThreshold); const outProducts = products.filter((product) => product.quantity === 0);
  return <ScreenContainer className="px-4" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View style={styles.storeMark}><MaterialIcons name="storefront" size={25} color="#FFFFFF" /></View><View style={styles.headerText}><Text style={styles.greeting}>مرحبًا بك</Text><Text style={styles.shopName}>{settings.shopName}</Text></View></View>
    <PrimaryButton title="مسح باركود للبيع" icon="qr-code-scanner" onPress={() => router.push("/scanner?mode=sale")} />
    <View style={styles.grid}><StatCard icon="inventory-2" label="إجمالي المنتجات" value={isReady ? String(products.length) : "—"} /><StatCard icon="warning-amber" label="منخفض المخزون" value={isReady ? String(lowProducts.length + outProducts.length) : "—"} tone="warning" /><StatCard icon="payments" label="مبيعات اليوم" value={isReady ? `${todaySales.toFixed(2)} ${settings.currency}` : "—"} tone="success" /><StatCard icon="account-balance-wallet" label="قيمة المخزون" value={isReady ? `${inventoryValue.toFixed(2)} ${settings.currency}` : "—"} /></View>
    <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>اختصارات سريعة</Text></View><View style={styles.actions}><PrimaryButton title="إضافة منتج" icon="add-box" onPress={() => router.push("/product/new")} outline /><PrimaryButton title="عرض المخزون" icon="warehouse" onPress={() => router.push("/stock")} outline /></View>
    <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>تنبيه المخزون</Text><Text style={styles.sectionHint}>الأقل من {settings.lowStockThreshold} وحدات</Text></View>{lowProducts.length + outProducts.length === 0 ? <EmptyState icon="verified" title="المخزون في وضع جيد" description="ستظهر المنتجات المنخفضة أو النافدة هنا لتتمكن من متابعتها بسرعة." /> : <View style={styles.productList}>{[...outProducts, ...lowProducts].slice(0, 4).map((product) => <ProductRow key={product.id} product={product} currency={settings.currency} onPress={() => router.push(`/product/${product.id}`)} />)}</View>}
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 14, paddingBottom: 28, gap: 17 }, header: { flexDirection: "row-reverse", alignItems: "center", gap: 11 }, storeMark: { width: 46, height: 46, borderRadius: 15, backgroundColor: "#146C5A", justifyContent: "center", alignItems: "center" }, headerText: { flex: 1, alignItems: "flex-end" }, greeting: { color: "#61726B", fontSize: 13, lineHeight: 18 }, shopName: { color: "#16201D", fontSize: 22, lineHeight: 29, fontWeight: "800" }, grid: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 10 }, sectionHeader: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", marginTop: 3 }, sectionTitle: { color: "#16201D", fontSize: 17, lineHeight: 24, fontWeight: "800" }, sectionHint: { color: "#728078", fontSize: 12, lineHeight: 18 }, actions: { gap: 10 }, productList: { gap: 9 } });
