import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { EmptyState, ProductRow } from "@/components/pos-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useInventory } from "@/lib/inventory/inventory-provider";

export default function ProductsScreen() {
  const { products, categories, settings } = useInventory(); const [query, setQuery] = useState(""); const [selectedCategory, setSelectedCategory] = useState<string | null>(null); const filtered = useMemo(() => { const normalized = query.trim().toLowerCase(); return products.filter((product) => (!normalized || product.name.toLowerCase().includes(normalized) || product.barcode?.toLowerCase().includes(normalized)) && (!selectedCategory || product.categoryId === selectedCategory)); }, [products, query, selectedCategory]);
  return <ScreenContainer className="px-4" containerClassName="bg-background"><View style={styles.header}><View style={styles.headerText}><Text style={styles.title}>المنتجات</Text><Text style={styles.subtitle}>{products.length} منتج محفوظ</Text></View><Pressable onPress={() => router.push("/product/new")} style={({ pressed }) => [styles.addButton, pressed && styles.pressed]}><MaterialIcons name="add" size={25} color="#FFFFFF" /></Pressable></View><View style={styles.search}><MaterialIcons name="search" size={22} color="#61726B" /><TextInput value={query} onChangeText={setQuery} placeholder="ابحث بالاسم أو الباركود" placeholderTextColor="#8D9B95" textAlign="right" style={styles.searchInput} returnKeyType="search" /></View><FlatList data={filtered} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListHeaderComponent={categories.length ? <FlatList horizontal inverted data={[{ id: "all", name: "الكل" }, ...categories]} keyExtractor={(item) => item.id} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips} renderItem={({ item }) => { const active = (item.id === "all" && !selectedCategory) || item.id === selectedCategory; return <Pressable onPress={() => setSelectedCategory(item.id === "all" ? null : item.id)} style={({ pressed }) => [styles.chip, active && styles.chipActive, pressed && styles.pressed]}><Text style={[styles.chipText, active && styles.chipTextActive]}>{item.name}</Text></Pressable>; }} /> : null} renderItem={({ item }) => <ProductRow product={item} currency={settings.currency} onPress={() => router.push(`/product/${item.id}`)} />} ItemSeparatorComponent={() => <View style={{ height: 9 }} />} ListEmptyComponent={<EmptyState icon="inventory-2" title={query ? "لا توجد نتائج" : "لا توجد منتجات بعد"} description={query ? "جرّب كتابة اسم آخر أو رقم باركود مختلف." : "ابدأ بإضافة أول منتج ليصبح جاهزًا للبيع بالمسح."} actionLabel={query ? undefined : "إضافة منتج"} onAction={query ? undefined : () => router.push("/product/new")} />} /></ScreenContainer>;
}
const styles = StyleSheet.create({ header: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", paddingTop: 12, paddingBottom: 13 }, headerText: { alignItems: "flex-end" }, title: { fontSize: 24, lineHeight: 31, color: "#16201D", fontWeight: "800" }, subtitle: { fontSize: 13, lineHeight: 18, color: "#61726B" }, addButton: { width: 45, height: 45, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#146C5A" }, pressed: { opacity: 0.72 }, search: { minHeight: 50, flexDirection: "row-reverse", alignItems: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E2EAE5", borderRadius: 14, paddingHorizontal: 14, gap: 8 }, searchInput: { flex: 1, color: "#16201D", fontSize: 15, lineHeight: 21, paddingVertical: 0 }, list: { paddingTop: 11, paddingBottom: 28, flexGrow: 1 }, chips: { gap: 8, paddingBottom: 12 }, chip: { paddingVertical: 8, paddingHorizontal: 13, borderRadius: 999, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E2EAE5" }, chipActive: { backgroundColor: "#E8F3EF", borderColor: "#146C5A" }, chipText: { color: "#61726B", fontSize: 13, lineHeight: 18, fontWeight: "700" }, chipTextActive: { color: "#146C5A" } });
