import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { EmptyState, PrimaryButton, ProductImage } from "@/components/pos-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useInventory } from "@/lib/inventory/inventory-provider";
type CartLine = { productId: string; quantity: number };

export default function SaleScreen() {
  const { scannedBarcode } = useLocalSearchParams<{ scannedBarcode?: string }>(); const { products, settings, createSale } = useInventory(); const [cart, setCart] = useState<CartLine[]>([]); const handledBarcode = useRef<string | null>(null);
  const lines = useMemo(() => cart.map((line) => ({ ...line, product: products.find((product) => product.id === line.productId) })).filter((line) => Boolean(line.product)) as (CartLine & { product: (typeof products)[number] })[], [cart, products]); const total = lines.reduce((sum, line) => sum + line.product.sellPrice * line.quantity, 0);
  const addProduct = useCallback((productId: string) => { const product = products.find((item) => item.id === productId); if (!product) return; setCart((current) => { const existing = current.find((item) => item.productId === productId); const nextQuantity = (existing?.quantity ?? 0) + 1; if (nextQuantity > product.quantity) { Alert.alert("كمية غير متوفرة", `المتاح من «${product.name}» هو ${product.quantity} فقط.`); return current; } return existing ? current.map((item) => item.productId === productId ? { ...item, quantity: nextQuantity } : item) : [...current, { productId, quantity: 1 }]; }); }, [products]);
  useEffect(() => { if (!scannedBarcode || handledBarcode.current === scannedBarcode) return; handledBarcode.current = scannedBarcode; const product = products.find((item) => item.barcode === scannedBarcode); if (product) addProduct(product.id); else Alert.alert("هذا المنتج غير مسجل", "هل تريد إضافته الآن؟", [{ text: "ليس الآن", style: "cancel" }, { text: "إضافة منتج", onPress: () => router.push(`/product/new?barcode=${encodeURIComponent(scannedBarcode)}`) }]); }, [addProduct, scannedBarcode, products]);
  const changeQuantity = (productId: string, delta: number) => { const product = products.find((item) => item.id === productId); if (!product) return; setCart((current) => current.flatMap((item) => { if (item.productId !== productId) return [item]; const next = item.quantity + delta; if (next <= 0) return []; if (next > product.quantity) { Alert.alert("كمية غير متوفرة", `المتاح هو ${product.quantity}.`); return [item]; } return [{ ...item, quantity: next }]; })); };
  const completeSale = async () => { try { await createSale(cart); setCart([]); Alert.alert("تمت عملية البيع", "تم تسجيل البيع وتحديث كميات المخزون بنجاح."); } catch (error) { Alert.alert("تعذر إتمام البيع", error instanceof Error ? error.message : "حدث خطأ غير متوقع."); } };
  const openScanner = () => router.push({ pathname: "/scanner", params: { mode: "sale" } } as never);
  return <ScreenContainer className="px-4" containerClassName="bg-background"><View style={styles.header}><View style={styles.headerText}><Text style={styles.title}>البيع السريع</Text><Text style={styles.subtitle}>{cart.length ? `${lines.length} منتجات في السلة` : "امسح الباركود لبدء البيع"}</Text></View><Pressable onPress={openScanner} style={({ pressed }) => [styles.scanButton, pressed && styles.pressed]}><MaterialIcons name="qr-code-scanner" size={25} color="#FFFFFF" /></Pressable></View>{!lines.length ? <EmptyState icon="qr-code-scanner" title="ابدأ بمسح باركود" description="وجّه الكاميرا نحو المنتج ليظهر تلقائيًا في سلة البيع." actionLabel="مسح باركود" onAction={openScanner} /> : <><FlatList data={lines} keyExtractor={(item) => item.productId} contentContainerStyle={styles.list} renderItem={({ item }) => <View style={styles.cartLine}><ProductImage product={item.product} size={48} /><View style={styles.lineInfo}><Text numberOfLines={1} style={styles.lineName}>{item.product.name}</Text><Text style={styles.linePrice}>{item.product.sellPrice.toFixed(2)} {settings.currency}</Text></View><View style={styles.quantityControl}><Pressable onPress={() => changeQuantity(item.productId, 1)} style={({ pressed }) => [styles.circleButton, pressed && styles.pressed]}><MaterialIcons name="add" size={19} color="#146C5A" /></Pressable><Text style={styles.lineQuantity}>{item.quantity}</Text><Pressable onPress={() => changeQuantity(item.productId, -1)} style={({ pressed }) => [styles.circleButton, pressed && styles.pressed]}><MaterialIcons name="remove" size={19} color="#146C5A" /></Pressable></View></View>} ItemSeparatorComponent={() => <View style={{ height: 9 }} />} /><View style={styles.checkout}><View style={styles.totalRow}><Text style={styles.totalLabel}>المجموع النهائي</Text><Text style={styles.total}>{total.toFixed(2)} {settings.currency}</Text></View><PrimaryButton title="إتمام عملية البيع" icon="check-circle" onPress={() => { void completeSale(); }} /></View></>}</ScreenContainer>;
}
const styles = StyleSheet.create({ header: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center", paddingTop: 12, paddingBottom: 15 }, headerText: { alignItems: "flex-end" }, title: { color: "#16201D", fontSize: 24, lineHeight: 31, fontWeight: "800" }, subtitle: { color: "#61726B", fontSize: 13, lineHeight: 19 }, scanButton: { width: 48, height: 48, alignItems: "center", justifyContent: "center", borderRadius: 15, backgroundColor: "#146C5A" }, pressed: { opacity: 0.75 }, list: { paddingBottom: 104 }, cartLine: { flexDirection: "row-reverse", gap: 10, alignItems: "center", padding: 11, borderWidth: 1, borderColor: "#E2EAE5", borderRadius: 16, backgroundColor: "#FFFFFF" }, lineInfo: { flex: 1, alignItems: "flex-end" }, lineName: { color: "#16201D", fontSize: 15, lineHeight: 21, fontWeight: "800", textAlign: "right", width: "100%" }, linePrice: { color: "#146C5A", fontSize: 13, lineHeight: 19, fontWeight: "700" }, quantityControl: { flexDirection: "row-reverse", alignItems: "center", gap: 6 }, circleButton: { width: 30, height: 30, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: "#E8F3EF" }, lineQuantity: { color: "#16201D", fontSize: 15, lineHeight: 21, fontWeight: "800", minWidth: 18, textAlign: "center" }, checkout: { position: "absolute", bottom: 13, left: 16, right: 16, padding: 14, gap: 12, borderWidth: 1, borderColor: "#D6E4DD", borderRadius: 19, backgroundColor: "#FFFFFF" }, totalRow: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, totalLabel: { color: "#61726B", fontSize: 14, lineHeight: 20, fontWeight: "700" }, total: { color: "#146C5A", fontSize: 21, lineHeight: 28, fontWeight: "800" } });
