import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { EmptyState, PrimaryButton, ProductImage } from "@/components/pos-ui";
import { ScreenContainer } from "@/components/screen-container";
import { MAX_CART_PRODUCTS, calculateCartTotal } from "@/lib/inventory/commerce";
import { useInventory, useSaleCart } from "@/lib/inventory/inventory-provider";

export default function SaleScreen() {
  const { products, settings, createSale } = useInventory(); const { cart, itemCount, setCartQuantity, clearCart } = useSaleCart(); const [editingProductId, setEditingProductId] = useState<string | null>(null); const [draftQuantity, setDraftQuantity] = useState("");
  const lines = useMemo(() => cart.map((line) => ({ ...line, product: products.find((product) => product.id === line.productId) })).filter((line): line is typeof line & { product: NonNullable<typeof line.product> } => Boolean(line.product)), [cart, products]); const total = calculateCartTotal(lines.map((line) => ({ unitPrice: line.product.sellPrice, quantity: line.quantity })));
  const showCartMessage = (reason: string, productName: string) => { if (reason === "capacity") Alert.alert("السلة ممتلئة", `يمكن للسلة استيعاب ${MAX_CART_PRODUCTS} صنفًا مختلفًا كحد أقصى.`); else if (reason === "unavailable") Alert.alert("كمية غير متوفرة", `المتاح من «${productName}» غير كافٍ.`); else if (reason === "invalid") Alert.alert("كمية غير صالحة", `أدخل كمية صحيحة بين 0 و${products.find((item) => item.name === productName)?.quantity ?? 0}.`); };
  const changeQuantity = (productId: string, nextQuantity: number) => { const product = products.find((item) => item.id === productId); const result = setCartQuantity(productId, nextQuantity); if (product && ["invalid", "unavailable", "capacity"].includes(result.reason)) showCartMessage(result.reason, product.name); };
  const startEdit = (productId: string, quantity: number) => { setEditingProductId(productId); setDraftQuantity(String(quantity)); };
  const commitEdit = (productId: string) => { const nextQuantity = Number(draftQuantity); changeQuantity(productId, nextQuantity); setEditingProductId(null); };
  const completeSale = async () => { try { await createSale(cart); clearCart(); Alert.alert("تمت عملية البيع", "تم تسجيل البيع وتحديث كميات المخزون بنجاح."); } catch (error) { Alert.alert("تعذر إتمام البيع", error instanceof Error ? error.message : "حدث خطأ غير متوقع."); } };
  const openScanner = () => router.push({ pathname: "/scanner", params: { mode: "sale" } } as never);
  return <ScreenContainer className="px-4" containerClassName="bg-background"><View style={styles.header}><View style={styles.headerText}><Text style={styles.title}>البيع السريع</Text><Text style={styles.subtitle}>{cart.length ? `${cart.length} أصناف • ${itemCount} وحدة` : "امسح الباركود لبدء البيع"}</Text></View><Pressable onPress={openScanner} style={({ pressed }) => [styles.scanButton, pressed && styles.pressed]}><MaterialIcons name="qr-code-scanner" size={25} color="#FFFFFF" /></Pressable></View><Pressable onPress={openScanner} style={({ pressed }) => [styles.scanBanner, pressed && styles.pressed]}><MaterialIcons name="qr-code-scanner" size={20} color="#146C5A" /><Text style={styles.scanBannerText}>امسح منتجًا واحدًا؛ تغلق الكاميرا بعد الإضافة</Text><MaterialIcons name="chevron-left" size={20} color="#146C5A" /></Pressable>{!lines.length ? <EmptyState icon="qr-code-scanner" title="ابدأ بمسح باركود" description="يمسح التطبيق منتجًا واحدًا، ثم يعود إلى سلة البيع تلقائيًا." actionLabel="مسح باركود" onAction={openScanner} /> : <><FlatList data={lines} keyExtractor={(item) => item.productId} contentContainerStyle={styles.list} renderItem={({ item }) => <View style={styles.cartLine}><ProductImage product={item.product} size={48} /><View style={styles.lineInfo}><Text numberOfLines={1} style={styles.lineName}>{item.product.name}</Text><Text style={styles.linePrice}>{item.product.sellPrice.toFixed(2)} {settings.currency} • المتاح {item.product.quantity}</Text></View><View style={styles.quantityControl}><Pressable onPress={() => changeQuantity(item.productId, item.quantity + 1)} style={({ pressed }) => [styles.circleButton, pressed && styles.pressed]}><MaterialIcons name="add" size={19} color="#146C5A" /></Pressable>{editingProductId === item.productId ? <TextInput value={draftQuantity} onChangeText={setDraftQuantity} onBlur={() => commitEdit(item.productId)} onSubmitEditing={() => commitEdit(item.productId)} autoFocus keyboardType="number-pad" selectTextOnFocus textAlign="center" style={styles.quantityInput} returnKeyType="done" /> : <Pressable onPress={() => startEdit(item.productId, item.quantity)} style={({ pressed }) => [styles.quantityButton, pressed && styles.pressed]}><Text style={styles.lineQuantity}>{item.quantity}</Text><MaterialIcons name="edit" size={13} color="#61726B" /></Pressable>}<Pressable onPress={() => changeQuantity(item.productId, item.quantity - 1)} style={({ pressed }) => [styles.circleButton, pressed && styles.pressed]}><MaterialIcons name="remove" size={19} color="#146C5A" /></Pressable></View></View>} ItemSeparatorComponent={() => <View style={{ height: 9 }} />} /><View style={styles.checkout}><View style={styles.totalRow}><Text style={styles.totalLabel}>المجموع النهائي</Text><Text style={styles.total}>{total.toFixed(2)} {settings.currency}</Text></View><PrimaryButton title="إتمام عملية البيع" icon="check-circle" onPress={() => { void completeSale(); }} /></View></>}</ScreenContainer>;
}

const styles = StyleSheet.create({ header: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center", paddingTop: 12, paddingBottom: 11 }, headerText: { alignItems: "flex-end" }, title: { color: "#16201D", fontSize: 24, lineHeight: 31, fontWeight: "800" }, subtitle: { color: "#61726B", fontSize: 13, lineHeight: 19 }, scanButton: { width: 48, height: 48, alignItems: "center", justifyContent: "center", borderRadius: 15, backgroundColor: "#146C5A" }, scanBanner: { minHeight: 46, marginBottom: 12, flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 13, borderRadius: 13, backgroundColor: "#E8F3EF" }, scanBannerText: { color: "#146C5A", fontSize: 13, lineHeight: 19, fontWeight: "800", flex: 1, textAlign: "right", paddingHorizontal: 8 }, pressed: { opacity: 0.75 }, list: { paddingBottom: 104 }, cartLine: { flexDirection: "row-reverse", gap: 10, alignItems: "center", padding: 11, borderWidth: 1, borderColor: "#E2EAE5", borderRadius: 16, backgroundColor: "#FFFFFF" }, lineInfo: { flex: 1, alignItems: "flex-end" }, lineName: { color: "#16201D", fontSize: 15, lineHeight: 21, fontWeight: "800", textAlign: "right", width: "100%" }, linePrice: { color: "#146C5A", fontSize: 12, lineHeight: 18, fontWeight: "700", textAlign: "right", width: "100%" }, quantityControl: { flexDirection: "row-reverse", alignItems: "center", gap: 5 }, circleButton: { width: 30, height: 30, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: "#E8F3EF" }, quantityButton: { minWidth: 41, height: 32, borderRadius: 10, paddingHorizontal: 6, flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 3, backgroundColor: "#F4F8F6", borderWidth: 1, borderColor: "#D8E4DE" }, lineQuantity: { color: "#16201D", fontSize: 15, lineHeight: 21, fontWeight: "800", textAlign: "center" }, quantityInput: { width: 44, height: 34, borderRadius: 10, borderWidth: 1.5, borderColor: "#146C5A", backgroundColor: "#FFFFFF", color: "#16201D", fontSize: 15, lineHeight: 20, fontWeight: "800", paddingHorizontal: 3 }, checkout: { position: "absolute", bottom: 13, left: 16, right: 16, padding: 14, gap: 12, borderWidth: 1, borderColor: "#D6E4DD", borderRadius: 19, backgroundColor: "#FFFFFF" }, totalRow: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, totalLabel: { color: "#61726B", fontSize: 14, lineHeight: 20, fontWeight: "700" }, total: { color: "#146C5A", fontSize: 21, lineHeight: 28, fontWeight: "800" } });
