import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as DocumentPicker from "expo-document-picker";
import * as Sharing from "expo-sharing";
import { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { PrimaryButton } from "@/components/pos-ui";
import { ScreenContainer } from "@/components/screen-container";
import { createBackupFile, restoreBackupFile } from "@/lib/inventory/backup";
import { useInventory } from "@/lib/inventory/inventory-provider";
import { useThemeContext } from "@/lib/theme-provider";

export default function SettingsScreen() {
  const { settings, saveSettings, refresh } = useInventory(); const { colorScheme, setColorScheme } = useThemeContext(); const [shopName, setShopName] = useState(settings.shopName); const [currency, setCurrency] = useState(settings.currency); const [threshold, setThreshold] = useState(String(settings.lowStockThreshold));
  useEffect(() => { setShopName(settings.shopName); setCurrency(settings.currency); setThreshold(String(settings.lowStockThreshold)); }, [settings]);
  const save = async (nextScheme = colorScheme) => { const numericThreshold = Number(threshold); if (!shopName.trim() || !currency.trim() || !Number.isInteger(numericThreshold) || numericThreshold < 0) { Alert.alert("بيانات غير مكتملة", "أدخل اسم المحل والعملة وحدًا صحيحًا للمخزون المنخفض."); return false; } await saveSettings({ shopName: shopName.trim(), currency: currency.trim(), lowStockThreshold: numericThreshold, colorScheme: nextScheme }); return true; };
  const toggleTheme = async (enabled: boolean) => { const next = enabled ? "dark" : "light"; setColorScheme(next); await save(next); };
  const backup = async () => { try { const uri = await createBackupFile(); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(uri, { dialogTitle: "حفظ نسخة احتياطية", mimeType: "application/json" }); else Alert.alert("تم إنشاء النسخة", "تم حفظ النسخة داخل مساحة التطبيق."); } catch { Alert.alert("تعذر إنشاء النسخة", "حاول مرة أخرى بعد التأكد من مساحة التخزين."); } };
  const restore = async () => { const result = await DocumentPicker.getDocumentAsync({ type: "application/json", copyToCacheDirectory: true }); if (result.canceled) return; Alert.alert("استعادة النسخة الاحتياطية", "سيتم استبدال البيانات الحالية في هذا الجهاز. هل تريد المتابعة؟", [{ text: "إلغاء", style: "cancel" }, { text: "استعادة", style: "destructive", onPress: async () => { try { await restoreBackupFile(result.assets[0].uri); await refresh(); Alert.alert("اكتملت الاستعادة", "تمت استعادة بيانات المتجر بنجاح."); } catch (error) { Alert.alert("تعذرت الاستعادة", error instanceof Error ? error.message : "ملف النسخة غير صالح."); } } }]); };
  return <ScreenContainer className="px-4" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.header}><Text style={styles.title}>الإعدادات</Text><Text style={styles.subtitle}>اضبط بيانات المحل وحماية بياناته</Text></View><Text style={styles.section}>بيانات المحل</Text><View style={styles.card}><Field icon="storefront" label="اسم المحل" value={shopName} onChangeText={setShopName} /><Field icon="payments" label="العملة" value={currency} onChangeText={setCurrency} /><Field icon="inventory" label="حد المخزون المنخفض" value={threshold} onChangeText={setThreshold} keyboardType="number-pad" /><PrimaryButton title="حفظ الإعدادات" icon="save" onPress={() => { void save().then((success) => success && Alert.alert("تم الحفظ", "تم تحديث إعدادات المحل.")); }} /></View><Text style={styles.section}>المظهر</Text><View style={styles.card}><View style={styles.settingRow}><View style={styles.rowText}><Text style={styles.rowTitle}>الوضع الداكن</Text><Text style={styles.rowHint}>تقليل سطوع الواجهة في الإضاءة المنخفضة</Text></View><Switch value={colorScheme === "dark"} onValueChange={(value) => { void toggleTheme(value); }} trackColor={{ false: "#C8D5CF", true: "#81CCB7" }} thumbColor={colorScheme === "dark" ? "#146C5A" : "#FFFFFF"} /></View></View><Text style={styles.section}>النسخ الاحتياطي والاستعادة</Text><View style={styles.card}><Pressable onPress={() => { void backup(); }} style={({ pressed }) => [styles.actionRow, pressed && styles.pressed]}><View style={styles.actionIcon}><MaterialIcons name="upload-file" size={23} color="#146C5A" /></View><View style={styles.rowText}><Text style={styles.rowTitle}>إنشاء نسخة احتياطية</Text><Text style={styles.rowHint}>احفظ نسخة من المنتجات والمبيعات والإعدادات</Text></View><MaterialIcons name="chevron-left" size={24} color="#7A8982" /></Pressable><View style={styles.divider} /><Pressable onPress={() => { void restore(); }} style={({ pressed }) => [styles.actionRow, pressed && styles.pressed]}><View style={[styles.actionIcon, { backgroundColor: "#FEF4DD" }]}><MaterialIcons name="restore" size={23} color="#B7791F" /></View><View style={styles.rowText}><Text style={styles.rowTitle}>استعادة نسخة احتياطية</Text><Text style={styles.rowHint}>استبدال بيانات هذا الجهاز من ملف محفوظ</Text></View><MaterialIcons name="chevron-left" size={24} color="#7A8982" /></Pressable></View><View style={styles.about}><Text style={styles.aboutTitle}>إدارة متجر</Text><Text style={styles.aboutText}>تطبيق محلي يعمل دون اتصال. تبقى بياناتك محفوظة على جهازك.</Text></View></ScrollView></ScreenContainer>;
}
function Field({ icon, label, value, onChangeText, keyboardType = "default" }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; label: string; value: string; onChangeText: (value: string) => void; keyboardType?: "default" | "number-pad" }) { return <View style={styles.field}><View style={styles.fieldLabel}><MaterialIcons name={icon} size={18} color="#61726B" /><Text style={styles.fieldLabelText}>{label}</Text></View><TextInput value={value} onChangeText={onChangeText} keyboardType={keyboardType} textAlign="right" style={styles.input} returnKeyType="done" /></View>; }
const styles = StyleSheet.create({ content: { paddingTop: 12, paddingBottom: 28, gap: 11 }, header: { alignItems: "flex-end", marginBottom: 3 }, title: { color: "#16201D", fontSize: 24, lineHeight: 31, fontWeight: "800" }, subtitle: { color: "#61726B", fontSize: 13, lineHeight: 19 }, section: { color: "#16201D", fontSize: 16, lineHeight: 23, fontWeight: "800", textAlign: "right", marginTop: 8 }, card: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E2EAE5", borderRadius: 17, padding: 14, gap: 13 }, field: { gap: 7 }, fieldLabel: { flexDirection: "row-reverse", gap: 6, alignItems: "center", justifyContent: "flex-start" }, fieldLabelText: { color: "#61726B", fontSize: 13, lineHeight: 19, fontWeight: "700" }, input: { minHeight: 45, borderRadius: 12, borderWidth: 1, borderColor: "#D8E4DE", paddingHorizontal: 12, color: "#16201D", fontSize: 15, lineHeight: 21, backgroundColor: "#FBFDFC" }, settingRow: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between" }, rowText: { alignItems: "flex-end", flex: 1, paddingHorizontal: 10 }, rowTitle: { color: "#16201D", fontSize: 15, lineHeight: 21, fontWeight: "800", textAlign: "right", width: "100%" }, rowHint: { color: "#728078", fontSize: 12, lineHeight: 18, textAlign: "right", width: "100%" }, actionRow: { minHeight: 56, flexDirection: "row-reverse", alignItems: "center" }, actionIcon: { width: 43, height: 43, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#E8F3EF" }, divider: { height: 1, backgroundColor: "#E8EFEB" }, pressed: { opacity: 0.7 }, about: { paddingVertical: 15, alignItems: "center", gap: 2 }, aboutTitle: { color: "#61726B", fontSize: 13, lineHeight: 18, fontWeight: "800" }, aboutText: { color: "#87958F", fontSize: 12, lineHeight: 18, textAlign: "center" } });
