import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { EmptyState, ProductRow, StatCard } from "@/components/pos-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useInventory } from "@/lib/inventory/inventory-provider";

export default function StockScreen() {
  const { products, settings } = useInventory(); const sorted = useMemo(() => [...products].sort((a, b) => a.quantity - b.quantity || a.name.localeCompare(b.name)), [products]); const outOfStock = products.filter((product) => product.quantity === 0).length; const lowStock = products.filter((product) => product.quantity > 0 && product.quantity <= settings.lowStockThreshold).length;
  const openProduct = (id: string) => router.push({ pathname: "/product/[id]", params: { id, focusQuantity: "1" } } as never);
  const openScanner = () => router.push({ pathname: "/scanner", params: { mode: "stock" } } as never);
  return <ScreenContainer className="px-4" containerClassName="bg-background"><View style={styles.header}><View style={styles.headerText}><Text style={styles.title}>المخزون</Text><Text style={styles.subtitle}>تابع الكميات وعدّلها سريعًا</Text></View><Pressable onPress={openScanner} style={({ pressed }) => [styles.scanButton, pressed && styles.pressed]}><MaterialIcons name="qr-code-scanner" size={23} color="#FFFFFF" /></Pressable></View><View style={styles.stats}><StatCard icon="production-quantity-limits" label="إجمالي الوحدات" value={String(products.reduce((sum, product) => sum + product.quantity, 0))} /><StatCard icon="warning-amber" label="منخفض أو نافد" value={String(lowStock + outOfStock)} tone="warning" /></View><Pressable onPress={openScanner} style={({ pressed }) => [styles.scanBanner, pressed && styles.pressed]}><MaterialIcons name="qr-code-scanner" size={20} color="#146C5A" /><Text style={styles.scanBannerText}>امسح باركود لتعديل كمية المنتج مباشرة</Text><MaterialIcons name="chevron-left" size={20} color="#146C5A" /></Pressable><View style={styles.listTitle}><MaterialIcons name="edit" size={16} color="#61726B" /><Text style={styles.listTitleText}>اضغط على المنتج لتعديل كميته</Text></View><FlatList data={sorted} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => <ProductRow product={item} currency={settings.currency} onPress={() => openProduct(item.id)} trailing={<View style={[styles.stockBadge, item.quantity === 0 ? styles.outBadge : item.quantity <= settings.lowStockThreshold ? styles.lowBadge : styles.goodBadge]}><Text style={[styles.stockText, item.quantity === 0 ? styles.outText : item.quantity <= settings.lowStockThreshold ? styles.lowText : styles.goodText]}>{item.quantity}</Text></View>} />} ItemSeparatorComponent={() => <View style={{ height: 9 }} />} ListEmptyComponent={<EmptyState icon="warehouse" title="المخزون فارغ" description="أضف منتجاتك أولًا، وستظهر كمياتها هنا." actionLabel="إضافة منتج" onAction={() => router.push({ pathname: "/product/[id]", params: { id: "new" } } as never)} />} /></ScreenContainer>;
}

const styles = StyleSheet.create({ header: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", paddingTop: 12, paddingBottom: 15 }, headerText: { alignItems: "flex-end" }, title: { fontSize: 24, lineHeight: 31, color: "#16201D", fontWeight: "800" }, subtitle: { fontSize: 13, lineHeight: 19, color: "#61726B" }, scanButton: { width: 46, height: 46, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#146C5A" }, stats: { flexDirection: "row-reverse", gap: 10 }, scanBanner: { minHeight: 46, marginTop: 12, flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 13, borderRadius: 13, backgroundColor: "#E8F3EF" }, scanBannerText: { color: "#146C5A", fontSize: 13, lineHeight: 19, fontWeight: "800", flex: 1, textAlign: "right", paddingHorizontal: 8 }, pressed: { opacity: 0.72 }, listTitle: { flexDirection: "row-reverse", gap: 5, alignItems: "center", justifyContent: "flex-start", marginTop: 17, marginBottom: 9 }, listTitleText: { fontSize: 13, lineHeight: 18, color: "#61726B" }, list: { paddingBottom: 26, flexGrow: 1 }, stockBadge: { minWidth: 42, height: 34, paddingHorizontal: 8, borderRadius: 11, alignItems: "center", justifyContent: "center" }, goodBadge: { backgroundColor: "#E7F5ED" }, lowBadge: { backgroundColor: "#FEF4DD" }, outBadge: { backgroundColor: "#FDE9EC" }, stockText: { fontSize: 14, lineHeight: 19, fontWeight: "800" }, goodText: { color: "#1F8A5B" }, lowText: { color: "#B7791F" }, outText: { color: "#C43D4B" } });
