import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo } from "react";
import { FlatList, StyleSheet, Text, View } from "react-native";
import { EmptyState, ProductRow, StatCard } from "@/components/pos-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useInventory } from "@/lib/inventory/inventory-provider";

export default function StockScreen() {
  const { products, settings } = useInventory(); const sorted = useMemo(() => [...products].sort((a, b) => a.quantity - b.quantity || a.name.localeCompare(b.name)), [products]); const outOfStock = products.filter((product) => product.quantity === 0).length; const lowStock = products.filter((product) => product.quantity > 0 && product.quantity <= settings.lowStockThreshold).length;
  return <ScreenContainer className="px-4" containerClassName="bg-background"><View style={styles.header}><Text style={styles.title}>المخزون</Text><Text style={styles.subtitle}>تابع الكميات وعدّلها سريعًا</Text></View><View style={styles.stats}><StatCard icon="production-quantity-limits" label="إجمالي الوحدات" value={String(products.reduce((sum, product) => sum + product.quantity, 0))} /><StatCard icon="warning-amber" label="منخفض أو نافد" value={String(lowStock + outOfStock)} tone="warning" /></View><View style={styles.listTitle}><MaterialIcons name="edit" size={16} color="#61726B" /><Text style={styles.listTitleText}>اضغط على المنتج لتعديل كميته</Text></View><FlatList data={sorted} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => <ProductRow product={item} currency={settings.currency} onPress={() => router.push(`/product/${item.id}`)} trailing={<View style={[styles.stockBadge, item.quantity === 0 ? styles.outBadge : item.quantity <= settings.lowStockThreshold ? styles.lowBadge : styles.goodBadge]}><Text style={[styles.stockText, item.quantity === 0 ? styles.outText : item.quantity <= settings.lowStockThreshold ? styles.lowText : styles.goodText]}>{item.quantity}</Text></View>} />} ItemSeparatorComponent={() => <View style={{ height: 9 }} />} ListEmptyComponent={<EmptyState icon="warehouse" title="المخزون فارغ" description="أضف منتجاتك أولًا، وستظهر كمياتها هنا." actionLabel="إضافة منتج" onAction={() => router.push("/product/new")} />} /></ScreenContainer>;
}
const styles = StyleSheet.create({ header: { alignItems: "flex-end", paddingTop: 12, paddingBottom: 15 }, title: { fontSize: 24, lineHeight: 31, color: "#16201D", fontWeight: "800" }, subtitle: { fontSize: 13, lineHeight: 19, color: "#61726B" }, stats: { flexDirection: "row-reverse", gap: 10 }, listTitle: { flexDirection: "row-reverse", gap: 5, alignItems: "center", justifyContent: "flex-start", marginTop: 17, marginBottom: 9 }, listTitleText: { fontSize: 13, lineHeight: 18, color: "#61726B" }, list: { paddingBottom: 26, flexGrow: 1 }, stockBadge: { minWidth: 42, height: 34, paddingHorizontal: 8, borderRadius: 11, alignItems: "center", justifyContent: "center" }, goodBadge: { backgroundColor: "#E7F5ED" }, lowBadge: { backgroundColor: "#FEF4DD" }, outBadge: { backgroundColor: "#FDE9EC" }, stockText: { fontSize: 14, lineHeight: 19, fontWeight: "800" }, goodText: { color: "#1F8A5B" }, lowText: { color: "#B7791F" }, outText: { color: "#C43D4B" } });
